# Generated by Django 6.0.6 on 2026-07-01 20:53

import django.db.models.deletion
import gates.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('townships', '0004_alter_townshipsetting_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='نام درب')),
                ('code', models.CharField(help_text='کد یکتای درب در سطح شهرک (مثال: GATE-01)', max_length=30, validators=[gates.validators.validate_gate_code], verbose_name='کد درب')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[gates.validators.validate_latitude], verbose_name='عرض جغرافیایی')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[gates.validators.validate_longitude], verbose_name='طول جغرافیایی')),
                ('township', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gates', to='townships.township', verbose_name='شهرک')),
            ],
            options={
                'verbose_name': 'درب',
                'verbose_name_plural': 'درب\u200cها',
                'db_table': 'gates',
                'ordering': ['township', 'name'],
                'indexes': [models.Index(fields=['township', 'is_active'], name='idx_gate_township_active'), models.Index(fields=['township', 'code'], name='idx_gate_township_code')],
                'constraints': [models.UniqueConstraint(fields=('township', 'code'), name='unique_gate_code_per_township'), models.CheckConstraint(condition=models.Q(models.Q(('latitude__isnull', True), ('longitude__isnull', True)), models.Q(('latitude__isnull', False), ('longitude__isnull', False)), _connector='OR'), name='gate_lat_lng_both_or_none')],
            },
        ),
    ]
