# Generated by Django 5.2.15 on 2026-06-30 08:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('townships', '0004_alter_townshipsetting_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('reservation_unit', models.CharField(choices=[('HOUR', 'ساعتی'), ('DAY', 'روزانه')], default='HOUR', max_length=10)),
                ('reservation_interval', models.PositiveIntegerField(default=60, help_text='دقیقه')),
                ('is_paid', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('township', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='townships.township')),
            ],
            options={
                'verbose_name': 'امکانات',
                'verbose_name_plural': 'امکانات',
                'db_table': 'facilities',
                'ordering': ['code'],
                'constraints': [models.UniqueConstraint(fields=('township', 'code'), name='unique_facility_code_per_township')],
            },
        ),
    ]
