# Generated by Django 5.2.15 on 2026-06-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='allow_cancellation',
            field=models.BooleanField(default=True, verbose_name='امکان لغو رزرو'),
        ),
        migrations.AddField(
            model_name='facility',
            name='available_from',
            field=models.TimeField(blank=True, null=True, verbose_name='شروع ساعت رزرو'),
        ),
        migrations.AddField(
            model_name='facility',
            name='available_until',
            field=models.TimeField(blank=True, null=True, verbose_name='پایان ساعت رزرو'),
        ),
        migrations.AddField(
            model_name='facility',
            name='cancellation_deadline_hours',
            field=models.PositiveSmallIntegerField(default=24, verbose_name='مهلت لغو (ساعت)'),
        ),
        migrations.AddField(
            model_name='facility',
            name='max_parallel_reservations',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='حداکثر رزرو همزمان'),
        ),
        migrations.AddField(
            model_name='facility',
            name='max_reservation_duration',
            field=models.PositiveSmallIntegerField(default=3, help_text='بر حسب واحد رزرو (ساعت یا روز)', verbose_name='حداکثر مدت هر رزرو'),
        ),
        migrations.AddField(
            model_name='facility',
            name='requires_approval',
            field=models.BooleanField(default=False, verbose_name='نیاز به تایید مدیر'),
        ),
    ]
