# Generated by Django 5.2.15 on 2026-06-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_facility_allow_cancellation_facility_available_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='reservation_policy',
            field=models.CharField(choices=[('EXCLUSIVE', 'فقط یک رزرو'), ('PER_VILLA', 'هر ویلا یک رزرو'), ('CAPACITY', 'بر اساس ظرفیت')], default='EXCLUSIVE', max_length=20, verbose_name='روش مدیریت رزرو'),
        ),
    ]
