# Generated by Django 5.2.15 on 2026-06-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_facility_reservation_policy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'ordering': ['code'], 'verbose_name': 'امکان', 'verbose_name_plural': 'امکانات'},
        ),
        migrations.AddField(
            model_name='facility',
            name='pricing_policy',
            field=models.CharField(choices=[('PER_RESERVATION', 'هر رزرو'), ('PER_PERSON', 'هر نفر'), ('PER_HOUR', 'هر ساعت'), ('PER_DAY', 'هر روز')], default='PER_RESERVATION', max_length=20, verbose_name='روش محاسبه قیمت'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='available_from',
            field=models.TimeField(blank=True, null=True, verbose_name='شروع ساعت کاری'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='available_until',
            field=models.TimeField(blank=True, null=True, verbose_name='پایان ساعت کاری'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='max_reservation_duration',
            field=models.PositiveSmallIntegerField(default=3, help_text='بر حسب واحد رزرو', verbose_name='حداکثر مدت رزرو'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='reservation_policy',
            field=models.CharField(choices=[('EXCLUSIVE', 'فقط یک رزرو'), ('PER_VILLA', 'هر ویلا یک رزرو'), ('CAPACITY', 'بر اساس ظرفیت')], default='EXCLUSIVE', max_length=20, verbose_name='روش رزرو'),
        ),
    ]
