# Generated by Django 5.2.15 on 2026-06-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_alter_facility_options_facility_pricing_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='allow_waiting_list',
            field=models.BooleanField(default=False, verbose_name='لیست انتظار'),
        ),
        migrations.AddField(
            model_name='facility',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد تخفیف'),
        ),
        migrations.AddField(
            model_name='facility',
            name='maximum_guest_count',
            field=models.PositiveSmallIntegerField(default=999, verbose_name='حداکثر نفرات'),
        ),
        migrations.AddField(
            model_name='facility',
            name='minimum_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='حداقل مبلغ قابل دریافت'),
        ),
        migrations.AddField(
            model_name='facility',
            name='minimum_guest_count',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='حداقل نفرات'),
        ),
        migrations.AddField(
            model_name='facility',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد مالیات'),
        ),
    ]
