# Generated by Django 5.2.15 on 2026-07-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0005_facility_allow_waiting_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='booking_mode',
            field=models.CharField(choices=[('TIME', 'بازه زمانی'), ('SLOT', 'سانسی')], default='TIME', max_length=10, verbose_name='نوع رزرو'),
        ),
    ]
