# Generated by Django 5.2.15 on 2026-06-29 19:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('townships', '0004_alter_townshipsetting_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('area', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('township', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villas', to='townships.township')),
            ],
            options={
                'verbose_name': 'ویلا',
                'verbose_name_plural': 'ویلاها',
                'db_table': 'villas',
                'ordering': ['code'],
                'constraints': [models.UniqueConstraint(fields=('township', 'code'), name='unique_villa_code_per_township')],
            },
        ),
    ]
