# Generated by Django 5.2.15 on 2026-06-29 19:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resident_type', models.CharField(choices=[('OWNER', 'مالک'), ('TENANT', 'مستأجر'), ('FAMILY', 'عضو خانواده')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residences', to=settings.AUTH_USER_MODEL)),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residences', to='villas.villa')),
            ],
            options={
                'verbose_name': 'سکونت',
                'verbose_name_plural': 'سکونت\u200cها',
                'db_table': 'residences',
                'ordering': ['villa', '-start_date'],
                'constraints': [models.UniqueConstraint(fields=('user', 'villa', 'resident_type', 'start_date'), name='unique_residence_record')],
            },
        ),
    ]
