# Generated by Django 5.2.15 on 2026-06-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villas', '0002_residence'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='family_count',
            field=models.PositiveSmallIntegerField(default=1, help_text='شامل مالک یا مستأجر نیز می\u200cشود.', verbose_name='تعداد افراد ساکن'),
        ),
    ]
