# Generated by Django 6.0.6 on 2026-07-07 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('townships', '0005_township_address_township_city_township_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='participants',
            new_name='members',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='message',
            name='edited_at',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='conversation_type',
            field=models.CharField(choices=[('PRIVATE', 'خصوصی'), ('GROUP', 'گروهی'), ('TOWNSHIP', 'شهرک')], default='PRIVATE', max_length=20),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='township',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='townships.township'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='conversation',
            table='chat_conversations',
        ),
        migrations.AlterModelTable(
            name='message',
            table='chat_messages',
        ),
    ]
