# Generated by Django 6.0.6 on 2026-07-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_conversation_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_muted',
            field=models.BooleanField(default=False),
        ),
    ]
