# Generated by Django 6.0.6 on 2026-07-08 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_conversation_is_starred_messagereaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='pinned_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chat.message'),
        ),
    ]
