# Generated by Django 5.2.15 on 2026-06-30 15:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0002_facility_allow_cancellation_facility_available_from_and_more'),
        ('villas', '0003_residence_family_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservation_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('reservation_status', models.CharField(choices=[('REQUESTED', 'درخواست شده'), ('APPROVED', 'تأیید شده'), ('REJECTED', 'رد شده'), ('CANCELLED', 'لغو شده'), ('COMPLETED', 'پایان یافته')], default='REQUESTED', max_length=20)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'پرداخت نشده'), ('PARTIAL', 'پرداخت ناقص'), ('PAID', 'پرداخت شده'), ('REFUNDED', 'عودت داده شده')], default='UNPAID', max_length=20)),
                ('price_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deposit_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True)),
                ('admin_note', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reservations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_reservations', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='facilities.facility')),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='villas.residence')),
            ],
            options={
                'verbose_name': 'رزرو',
                'verbose_name_plural': 'رزروها',
                'db_table': 'reservations',
                'ordering': ['-start_datetime'],
            },
        ),
    ]
