# Generated by Django 5.2.15 on 2026-06-30 20:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_guest_count_reservation_total_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('CREATED', 'ایجاد'), ('APPROVED', 'تایید'), ('CANCELLED', 'لغو'), ('REJECTED', 'رد'), ('EDITED', 'ویرایش'), ('PAYMENT', 'پرداخت'), ('REFUND', 'استرداد')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='reservations.reservation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تاریخچه رزرو',
                'verbose_name_plural': 'تاریخچه رزروها',
                'db_table': 'reservation_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
