# Generated by Django 5.2.15 on 2026-07-01 08:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservationlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='checked_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='extra_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='reservation',
            name='late_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='reservation',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='reservationlog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'ایجاد'), ('APPROVED', 'تایید'), ('CANCELLED', 'لغو'), ('REJECTED', 'رد'), ('EDITED', 'ویرایش'), ('PAYMENT', 'پرداخت'), ('REFUND', 'استرداد'), ('AUTO_APPROVED', 'تایید خودکار'), ('ADMIN_APPROVED', 'تایید مدیر'), ('EXPIRED', 'منقضی'), ('ADMIN_CANCELLED', 'لغو توسط مدیر'), ('CHECK_IN', 'ورود'), ('CHECK_OUT', 'خروج')], max_length=20),
        ),
        migrations.CreateModel(
            name='ReservationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('CASH', 'نقدی'), ('CARD', 'کارتخوان'), ('ONLINE', 'درگاه بانکی'), ('TRANSFER', 'واریز')], max_length=20)),
                ('payment_type', models.CharField(choices=[('DEPOSIT', 'بیعانه'), ('PAYMENT', 'پرداخت'), ('REFUND', 'استرداد')], default='PAYMENT', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='reservations.reservation')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'db_table': 'reservation_payments',
                'ordering': ['-paid_at'],
            },
        ),
    ]
