# Generated by Django 5.2.15 on 2026-07-01 08:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0006_facility_booking_mode'),
        ('reservations', '0004_reservation_cancelled_at_reservation_cancelled_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationlog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'ایجاد'), ('APPROVED', 'تایید'), ('CANCELLED', 'لغو'), ('REJECTED', 'رد'), ('EDITED', 'ویرایش'), ('PAYMENT', 'پرداخت'), ('REFUND', 'استرداد'), ('AUTO_APPROVED', 'تایید خودکار'), ('ADMIN_APPROVED', 'تایید مدیر'), ('EXPIRED', 'منقضی'), ('ADMIN_CANCELLED', 'لغو توسط مدیر'), ('CHECK_IN', 'ورود'), ('CHECK_OUT', 'خروج'), ('PARTIAL_PAYMENT', 'پرداخت ناقص'), ('FULL_PAYMENT', 'تسویه کامل'), ('REFUND_PAYMENT', 'استرداد')], max_length=20),
        ),
        migrations.CreateModel(
            name='ReservationSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=1)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='facilities.facility')),
            ],
            options={
                'verbose_name': 'سانس',
                'verbose_name_plural': 'سانس\u200cها',
                'db_table': 'reservation_slots',
                'ordering': ['sort_order', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='reservations.reservationslot'),
        ),
    ]
