# Generated by Django 6.0.6 on 2026-07-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_alter_reservationlog_action_reservationslot_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservationpayment',
            options={'ordering': ['-created_at'], 'verbose_name': 'پرداخت', 'verbose_name_plural': 'پرداخت\u200cها'},
        ),
        migrations.RemoveField(
            model_name='reservationpayment',
            name='paid_at',
        ),
        migrations.AlterField(
            model_name='reservationlog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'ایجاد'), ('APPROVED', 'تایید'), ('CANCELLED', 'لغو'), ('REJECTED', 'رد'), ('EDITED', 'ویرایش'), ('PAYMENT', 'پرداخت'), ('REFUND', 'استرداد'), ('AUTO_APPROVED', 'تایید خودکار'), ('ADMIN_APPROVED', 'تایید مدیر'), ('EXPIRED', 'منقضی'), ('ADMIN_CANCELLED', 'لغو توسط مدیر'), ('CHECK_IN', 'ورود'), ('CHECK_OUT', 'خروج'), ('PARTIAL_PAYMENT', 'پرداخت ناقص'), ('FULL_PAYMENT', 'تسویه کامل'), ('REFUND_PAYMENT', 'استرداد'), ('COMPLETED', 'پایان خودکار')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reservationpayment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'نقدی'), ('CARD', 'کارتخوان'), ('ONLINE', 'آنلاین'), ('TRANSFER', 'واریز')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reservationpayment',
            name='payment_type',
            field=models.CharField(choices=[('PAYMENT', 'پرداخت'), ('REFUND', 'استرداد')], default='PAYMENT', max_length=20),
        ),
    ]
