# Generated by Django 5.2.15 on 2026-06-28 19:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_permission_role_membership'),
        ('townships', '0003_alter_township_options_alter_township_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='permission',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='description',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='name',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='role',
            name='code',
        ),
        migrations.RemoveField(
            model_name='role',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='role',
            name='description',
        ),
        migrations.RemoveField(
            model_name='role',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='role',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='role',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='township',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='uuid',
        ),
        migrations.AddField(
            model_name='permission',
            name='roles',
            field=models.ManyToManyField(related_name='permissions', to='accounts.role'),
        ),
        migrations.AddField(
            model_name='permission',
            name='title',
            field=models.CharField(default='بدون عنوان', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='active_township',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='townships.township'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.role'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterModelTable(
            name='membership',
            table=None,
        ),
        migrations.AlterModelTable(
            name='permission',
            table=None,
        ),
        migrations.AlterModelTable(
            name='role',
            table=None,
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.role')),
                ('township', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='townships.township')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='membership',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='joined_at',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='uuid',
        ),
    ]
