# Generated by Django 5.2.15 on 2026-06-29 10:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_membership_unique_together'),
        ('townships', '0004_alter_townshipsetting_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitation',
            options={'verbose_name': 'دعوت\u200cنامه', 'verbose_name_plural': 'دعوت\u200cنامه\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': 'عضویت', 'verbose_name_plural': 'عضویت\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'verbose_name': 'مجوز', 'verbose_name_plural': 'مجوزها'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'نقش', 'verbose_name_plural': 'نقش\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='email',
        ),
        migrations.AddField(
            model_name='invitation',
            name='mobile',
            field=models.CharField(default='null', max_length=15, verbose_name='شماره موبایل'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(db_index=True, default='09120000000', max_length=15, unique=True, verbose_name='شماره موبایل'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invitation',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='استفاده شده'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.role', verbose_name='نقش'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='township',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='townships.township', verbose_name='شهرک'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='permissions', to='accounts.role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='active_township',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='townships.township', verbose_name='شهرک فعال'),
        ),
    ]
