# Generated by Django 6.0.6 on 2026-07-02 08:32

import access_logs.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gates', '0001_initial'),
        ('guards', '0001_initial'),
        ('townships', '0004_alter_townshipsetting_table'),
        ('villas', '0003_residence_family_count'),
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('IN', 'ورود'), ('OUT', 'خروج')], max_length=10, verbose_name='جهت تردد')),
                ('access_method', models.CharField(choices=[('MANUAL', 'ثبت دستی توسط نگهبان'), ('QR', 'کد QR'), ('PLATE', 'تشخیص پلاک'), ('CARD', 'کارت تردد')], default='MANUAL', max_length=20, verbose_name='روش ثبت')),
                ('plate_number', models.CharField(blank=True, max_length=30, validators=[access_logs.validators.validate_plate_number], verbose_name='پلاک خودرو')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان تردد')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('gate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_logs', to='gates.gate', verbose_name='درب')),
                ('guard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='guards.guard', verbose_name='نگهبان ثبت\u200cکننده')),
                ('residence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='villas.residence', verbose_name='سکونت (ساکن)')),
                ('township', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='townships.township', verbose_name='شهرک')),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='visitors.visitor', verbose_name='مهمان')),
            ],
            options={
                'verbose_name': 'رویداد تردد',
                'verbose_name_plural': 'رویدادهای تردد',
                'db_table': 'access_logs',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['township', 'occurred_at'], name='idx_accesslog_township_time'), models.Index(fields=['gate', 'occurred_at'], name='idx_accesslog_gate_time'), models.Index(fields=['visitor'], name='idx_accesslog_visitor'), models.Index(fields=['residence'], name='idx_accesslog_residence')],
                'constraints': [models.CheckConstraint(condition=models.Q(('visitor__isnull', False), ('residence__isnull', False), _negated=True), name='access_log_visitor_xor_residence')],
            },
        ),
    ]
