# Generated by Django 6.0.6 on 2026-07-08 08:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('townships', '0005_township_address_township_city_township_description_and_more'),
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monthly_subscription', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transaction_percent', models.DecimalField(decimal_places=2, default=2, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('township', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission_rule', to='townships.township')),
            ],
            options={
                'db_table': 'wallet_commission_rules',
            },
        ),
        migrations.CreateModel(
            name='CommissionTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('township', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='townships.township')),
                ('wallet_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='wallets.wallettransaction')),
            ],
            options={
                'db_table': 'wallet_commissions',
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid')], default='PENDING', max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_owner', models.CharField(blank=True, max_length=150)),
                ('card_number', models.CharField(blank=True, max_length=20)),
                ('sheba_number', models.CharField(blank=True, max_length=30)),
                ('tracking_code', models.CharField(blank=True, max_length=100)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='wallets.wallet')),
            ],
            options={
                'db_table': 'wallet_settlements',
                'ordering': ['-created_at'],
            },
        ),
    ]
