# Generated by Django 6.0.6 on 2026-07-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_paymentgateway_gatewaytransaction_gatewaycallback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='authority',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='failure_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='gateway_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='gateway_ref_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
