# Generated by Django 6.0.6 on 2026-07-09 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('wallets', '0004_wallettransaction_authority_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentgateway',
            options={'ordering': ['priority']},
        ),
        migrations.RenameField(
            model_name='gatewaytransaction',
            old_name='success',
            new_name='is_verified',
        ),
        migrations.RenameField(
            model_name='gatewaytransaction',
            old_name='verified',
            new_name='is_wallet_updated',
        ),
        migrations.RemoveField(
            model_name='gatewaycallback',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='paymentgateway',
            name='callback_url',
        ),
        migrations.AddField(
            model_name='gatewaytransaction',
            name='raw_request',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gatewaytransaction',
            name='raw_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gatewaytransaction',
            name='wallet_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gateway_transactions', to='wallets.wallettransaction'),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='priority',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='production_merchant_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='sandbox_merchant_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='gateway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallets.paymentgateway'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='sandbox',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='paymentgateway',
            table=None,
        ),
    ]
