# Generated by Django 6.0.6 on 2026-07-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0005_alter_paymentgateway_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgateway',
            name='callback_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='payment_gateways/'),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='payment_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='verify_url',
            field=models.URLField(blank=True),
        ),
    ]
