# Generated by Django 6.0.6 on 2026-07-10 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0006_paymentgateway_callback_url_paymentgateway_icon_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdrawalrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='paid',
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='account_owner',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_withdrawals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='bank_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='card_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_withdrawals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='reject_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='sheba_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='wallet_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdraw_request', to='wallets.wallettransaction'),
        ),
    ]
