# Generated by Django 6.0.6 on 2026-07-02 09:02

import access_control.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gates', '0001_initial'),
        ('guards', '0001_initial'),
        ('townships', '0004_alter_townshipsetting_table'),
        ('visitors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='کد QR')),
                ('valid_from', models.DateTimeField(verbose_name='اعتبار از')),
                ('valid_until', models.DateTimeField(verbose_name='اعتبار تا')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار تایید'), ('APPROVED', 'تایید شده'), ('REJECTED', 'رد شده'), ('CANCELLED', 'لغو شده'), ('CHECKED_IN', 'ورود ثبت\u200cشده'), ('CHECKED_OUT', 'خروج ثبت\u200cشده'), ('EXPIRED', 'منقضی')], default='PENDING', max_length=20, verbose_name='وضعیت')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تایید')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ورود')),
                ('checked_out_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان خروج')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_access_passes', to=settings.AUTH_USER_MODEL, verbose_name='تاییدکننده')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_access_passes', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('gate', models.ForeignKey(blank=True, help_text='در صورت خالی بودن، کارت از هر دربی قابل استفاده است.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_passes', to='gates.gate', verbose_name='درب مجاز')),
                ('township', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_passes', to='townships.township', verbose_name='شهرک')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_passes', to='visitors.visitor', verbose_name='مهمان')),
            ],
            options={
                'verbose_name': 'کارت تردد',
                'verbose_name_plural': 'کارت\u200cهای تردد',
                'db_table': 'access_passes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('CHECK_IN', 'ورود'), ('CHECK_OUT', 'خروج'), ('DENIED', 'رد شده'), ('QR_SCAN', 'اسکن QR'), ('MANUAL', 'ثبت دستی'), ('MANAGER', 'اقدام مدیر')], max_length=20, verbose_name='عملیات')),
                ('device', models.CharField(blank=True, help_text='شناسه دستگاه/اپلیکیشن ثبت\u200cکننده (مثال: QR-SCANNER-01)', max_length=100, validators=[access_control.validators.validate_device_label], verbose_name='دستگاه')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[access_control.validators.validate_latitude], verbose_name='عرض جغرافیایی')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[access_control.validators.validate_longitude], verbose_name='طول جغرافیایی')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('gate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_control_logs', to='gates.gate', verbose_name='درب')),
                ('guard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_control_logs', to='guards.guard', verbose_name='نگهبان ثبت\u200cکننده')),
                ('township', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_control_logs', to='townships.township', verbose_name='شهرک')),
                ('access_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='access_control.accesspass', verbose_name='کارت تردد')),
            ],
            options={
                'verbose_name': 'رویداد کنترل تردد',
                'verbose_name_plural': 'رویدادهای کنترل تردد',
                'db_table': 'access_control_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='accesspass',
            index=models.Index(fields=['township', 'status'], name='idx_apass_township_status'),
        ),
        migrations.AddIndex(
            model_name='accesspass',
            index=models.Index(fields=['gate', 'status'], name='idx_apass_gate_status'),
        ),
        migrations.AddIndex(
            model_name='accesspass',
            index=models.Index(fields=['visitor'], name='idx_apass_visitor'),
        ),
        migrations.AddIndex(
            model_name='accesspass',
            index=models.Index(fields=['valid_from', 'valid_until'], name='idx_apass_valid_period'),
        ),
        migrations.AddConstraint(
            model_name='accesspass',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__gt', models.F('valid_from'))), name='access_pass_valid_until_after_valid_from'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['township', 'created_at'], name='idx_aclog_township_time'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['gate', 'created_at'], name='idx_aclog_gate_time'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['access_pass', 'created_at'], name='idx_aclog_pass_time'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['action'], name='idx_aclog_action'),
        ),
        migrations.AddConstraint(
            model_name='accesslog',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('latitude__isnull', True), ('longitude__isnull', True)), models.Q(('latitude__isnull', False), ('longitude__isnull', False)), _connector='OR'), name='access_log_lat_lng_both_or_none'),
        ),
    ]
