# Generated by Django 6.0.6 on 2026-07-01 20:53

import django.db.models.deletion
import guards.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gates', '0001_initial'),
        ('townships', '0004_alter_townshipsetting_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_code', models.CharField(max_length=30, unique=True, validators=[guards.validators.validate_employee_code], verbose_name='کد پرسنلی')),
                ('phone', models.CharField(max_length=20, validators=[guards.validators.validate_guard_phone], verbose_name='تلفن')),
                ('shift', models.CharField(choices=[('MORNING', 'صبح'), ('EVENING', 'عصر'), ('NIGHT', 'شب')], max_length=20, verbose_name='شیفت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('hired_at', models.DateField(blank=True, null=True, verbose_name='تاریخ استخدام')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('gates', models.ManyToManyField(blank=True, related_name='guards', to='gates.gate', verbose_name='درب\u200cهای تحت مسئولیت')),
                ('township', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guards', to='townships.township', verbose_name='شهرک')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guard_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نگهبان',
                'verbose_name_plural': 'نگهبان\u200cها',
                'db_table': 'guards',
                'ordering': ['township', 'employee_code'],
            },
        ),
        migrations.CreateModel(
            name='GuardLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('LOGIN', 'ورود'), ('LOGOUT', 'خروج'), ('CHECKIN', 'ثبت ورود'), ('CHECKOUT', 'ثبت خروج'), ('GATE_ASSIGNED', 'تخصیص درب'), ('GATE_REMOVED', 'حذف تخصیص درب'), ('ACTIVATED', 'فعال\u200cسازی'), ('DEACTIVATED', 'غیرفعال\u200cسازی'), ('MANUAL', 'عملیات دستی')], max_length=20, verbose_name='عملیات')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='guards.guard', verbose_name='نگهبان')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guard_logs_performed', to=settings.AUTH_USER_MODEL, verbose_name='انجام\u200cشده توسط')),
            ],
            options={
                'verbose_name': 'رویداد نگهبان',
                'verbose_name_plural': 'رویدادهای نگهبان',
                'db_table': 'guard_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuardShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(verbose_name='زمان شروع')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان')),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='guards.guard', verbose_name='نگهبان')),
            ],
            options={
                'verbose_name': 'شیفت نگهبان',
                'verbose_name_plural': 'شیفت\u200cهای نگهبان',
                'db_table': 'guard_shifts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='guard',
            index=models.Index(fields=['township', 'is_active'], name='idx_guard_township_active'),
        ),
        migrations.AddConstraint(
            model_name='guardshift',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('guard',), name='unique_open_shift_per_guard'),
        ),
        migrations.AddConstraint(
            model_name='guardshift',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gt', models.F('started_at')), _connector='OR'), name='guard_shift_end_after_start'),
        ),
    ]
