# Generated by Django 5.2.15 on 2026-07-01 18:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('townships', '0004_alter_townshipsetting_table'),
        ('villas', '0003_residence_family_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visitor_type', models.CharField(choices=[('GUEST', 'مهمان'), ('CONTRACTOR', 'پیمانکار'), ('DELIVERY', 'پیک'), ('SERVICE', 'سرویس'), ('STAFF', 'پرسنل'), ('OTHER', 'سایر')], default='GUEST', max_length=20)),
                ('full_name', models.CharField(max_length=200)),
                ('national_code', models.CharField(blank=True, max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('adult_count', models.PositiveIntegerField(default=1)),
                ('child_count', models.PositiveIntegerField(default=0)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('status', models.CharField(choices=[('REQUESTED', 'درخواست شده'), ('APPROVED', 'تایید شده'), ('REJECTED', 'رد شده'), ('CANCELLED', 'لغو شده'), ('CHECKED_IN', 'ورود'), ('CHECKED_OUT', 'خروج'), ('EXPIRED', 'منقضی')], default='REQUESTED', max_length=20)),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_visitors', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_visitors', to=settings.AUTH_USER_MODEL)),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='villas.residence')),
                ('township', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='townships.township')),
            ],
            options={
                'verbose_name': 'مهمان',
                'verbose_name_plural': 'مهمان\u200cها',
                'db_table': 'visitors',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('CREATED', 'ایجاد'), ('APPROVED', 'تایید'), ('REJECTED', 'رد'), ('CANCELLED', 'لغو'), ('CHECK_IN', 'ورود'), ('CHECK_OUT', 'خروج'), ('EDITED', 'ویرایش')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='visitors.visitor')),
            ],
            options={
                'db_table': 'visitor_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitorVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plate_number', models.CharField(max_length=30)),
                ('car_model', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='visitors.visitor')),
            ],
            options={
                'verbose_name': 'خودرو مهمان',
                'verbose_name_plural': 'خودروهای مهمان',
                'db_table': 'visitor_vehicles',
            },
        ),
    ]
