# Generated by Django 5.2.15 on 2026-06-27 20:41

import django.db.models.deletion
import townships.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('townships', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='township',
            options={'ordering': ['name'], 'verbose_name': 'Township', 'verbose_name_plural': 'Townships'},
        ),
        migrations.AddField(
            model_name='township',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=townships.models.township_logo_path, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='township',
            name='code',
            field=models.CharField(db_index=True, help_text='Unique code used to identify the township.', max_length=20, unique=True, verbose_name='Township Code'),
        ),
        migrations.AlterField(
            model_name='township',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='township',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Township Name'),
        ),
        migrations.AlterModelTable(
            name='township',
            table='townships',
        ),
        migrations.CreateModel(
            name='TownshipSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_color', models.CharField(default='#1976D2', max_length=7)),
                ('secondary_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('reservation_enabled', models.BooleanField(default=True)),
                ('online_payment_enabled', models.BooleanField(default=False)),
                ('guest_access_enabled', models.BooleanField(default=False)),
                ('township', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='townships.township')),
            ],
            options={
                'db_table': 'township_settings',
            },
        ),
    ]
