# Generated by Django 5.2.15 on 2026-06-28 19:26

import townships.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('townships', '0002_alter_township_options_township_logo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='township',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='township',
            name='code',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='township',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='township',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=townships.models.township_logo_path),
        ),
        migrations.AlterField(
            model_name='township',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='township',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='townshipsetting',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterModelTable(
            name='townshipsetting',
            table=None,
        ),
    ]
