# Generated by Django 5.2.15 on 2026-06-28 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('townships', '0003_alter_township_options_alter_township_code_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='townshipsetting',
            table='township_settings',
        ),
    ]
