# Generated by Django 6.0.6 on 2026-07-07 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('townships', '0004_alter_townshipsetting_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='township',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='township',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='township',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='township',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='township',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_townships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='township',
            name='mobile',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='township',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='township',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='township',
            name='province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='township',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='townshipsetting',
            name='ai_assistant_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='townshipsetting',
            name='announcements_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='townshipsetting',
            name='chat_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='townshipsetting',
            name='marketplace_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='townshipsetting',
            name='max_storage_gb',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='townshipsetting',
            name='max_users',
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AddField(
            model_name='townshipsetting',
            name='polls_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='townshipsetting',
            name='private_chat_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
