# Generated by Django 5.2.15 on 2026-07-01 18:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('RESERVATION', 'رزرو'), ('PAYMENT', 'پرداخت'), ('CHARGE', 'شارژ'), ('COMPLAINT', 'شکایت'), ('VISITOR', 'مهمان'), ('ANNOUNCEMENT', 'اطلاعیه'), ('SYSTEM', 'سیستم')], default='SYSTEM', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'کم'), ('NORMAL', 'عادی'), ('HIGH', 'زیاد'), ('URGENT', 'فوری')], default='NORMAL', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار'), ('SENT', 'ارسال شده'), ('FAILED', 'ناموفق'), ('CANCELLED', 'لغو شده')], default='PENDING', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلان\u200cها',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('IN_APP', 'داخل برنامه'), ('SMS', 'پیامک'), ('EMAIL', 'ایمیل'), ('PUSH', 'Push')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار'), ('SENDING', 'در حال ارسال'), ('SENT', 'ارسال شده'), ('FAILED', 'ناموفق')], default='PENDING', max_length=20)),
                ('receiver', models.CharField(max_length=255)),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications.notification')),
            ],
            options={
                'verbose_name': 'گزارش اعلان',
                'verbose_name_plural': 'گزارش اعلان\u200cها',
                'db_table': 'notification_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
